export const env = {
  MOVIES_POPULAR: 'https://api.themoviedb.org/3/movie/popular',
  MOVIES_NOW: 'https://api.themoviedb.org/3/movie/now_playing',
  MOVIES_TOP_RATED: 'https://api.themoviedb.org/3/movie/top_rated',
  MOVIES_UPCOMING: 'https://api.themoviedb.org/3/movie/upcoming',
  TRENDING_MOVIE_DAY: 'https://api.themoviedb.org/3/trending/movie/day',
  TRENDING_TV: 'https://api.themoviedb.org/3/trending/tv/day',
  MOVIE: 'https://api.themoviedb.org/3/movie/',
  DISCOVER_MOVIE: 'https://api.themoviedb.org/3/discover/movie',
  DISCOVER_TV: 'https://api.themoviedb.org/3/discover/tv',
  GENRE: 'https://api.themoviedb.org/3/genre/movie/list',
  SEARCH_MOVIE: 'https://api.themoviedb.org/3/search/movie',
  SEARCH_TV: 'https://api.themoviedb.org/3/search/tv',
  TV_SHOWS: 'https://api.themoviedb.org/3/tv/popular',
  TV_SHOWS_TOP: 'https://api.themoviedb.org/3/tv/top_rated',
  TV_SHOW: 'https://api.themoviedb.org/3/tv/',
};
